name: nbval-partial-test
on:
  push:
    paths:
      - "**.ipynb"
jobs:
  nbval-partial-demo:
    runs-on: ubuntu-latest
    container:
      image: ouvocl/vce-tm351-monolith
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 0 # or 2?
#        ref: nbval-test-tags
    - id: changed-files
      uses: tj-actions/changed-files@v11.1
      with:
          files: |
            .ipynb$
    - name: Install nbval (TH edition)
      run: |
        python3 -m pip install --upgrade git+https://github.com/ouseful-PR/nbval.git@table-test
        #python3 -m pip install --upgrade git+https://github.com/innovationOUtside/nb_workflow_tools.git
    - name: Restart postgres
      run: |
        sudo service postgresql restart
    - name: Start mongo
      run: |
        sudo mongod --fork --logpath /dev/stdout --dbpath ${MONGO_DB_PATH}
    - name: test changed files
      run: |
        for file in "${{ steps.changed-files.outputs.all_modified_files }}"; do
            py.test  --nbval "$file" || continue
          done
        done
