name: nbval-tm351-22j-test
on:
  workflow_dispatch

jobs:
  nbval-demo:
    runs-on: ubuntu-latest
    container:
      image: ouvocl/vce-tm351-jh:22j-b6
      options: --user root
    steps:
    - uses: actions/checkout@v1
    - name: Install nbval (TH edition)
      run: |
        python3 -m pip install --upgrade https://github.com/ouseful-PR/nbval/archive/table-test.zip
# Following doesn't work in Github Action
#    - name: Mock entrypoint
#      run: |
#        /usr/local/bin/repo2docker-entrypoint tini -g --
# So instead we have to manually do what the original startup script did
# For the jh container, we also need to update paths as they get updated at start-time...
    - name: Restart postgres
      run: |
        PGDATA=/home/jovyan/.postgres/12/main
        sudo service postgresql restart
    - name: Start mongo
      run: |
        # Whilst we debug...
        #sudo mongod --logpath /dev/stdout --dbpath ${MONGO_DB_PATH}
        MONGO_DB_PATH=/home/jovyan/.mongo/
        sudo mongod --fork --logpath /dev/stdout --dbpath ${MONGO_DB_PATH}
    - name: Run basic tests
      run: |
        py.test --nbval test.ipynb
      # The following line means that the action will continue rather than fail if this step fails
      continue-on-error: true
    - name: TM351 installation test
      run: |
        py.test --nbval TM351_Container_Test.ipynb
